add more test cases for convertSpreadsheetToJson
dadosjusbr/parser pull request #4
Opened 2019-02-01 03:52 UTC by viniagostini

2019-02-01 14:47 UTC, danielfireman requested changes

2019-02-01 14:47 UTC, danielfireman commented on test/spreadsheets.js
> +const { readFileAsync } = require('./test_utils');
Não acho que esse arquivo seja necessário. Até essas constantes serem usadas por outros testes vamos simplificar e colocar tudo no mesmo arquivo.

2019-02-01 14:47 UTC, danielfireman commented on test/xlsx_service.test.js
> +
Pergunta: Precisa mesmo de todas essas linhas em branco num teste tão simples? Perguntando pois o teste abaixo não tem nenhuma linha em branco.

2019-02-04 14:26 UTC, viniagostini commented on test/xlsx_service.test.js
> +
Eu normalmente divido a maior parte dos meus testes da seguinte forma: 
1) Criar o conteúdo necessário para passar para a função/método/funcionalidade que vou testar.
2) Caso a resposta seja um objeto mais complexo, criar o objeto esperado na resposta.
3) Chamar a função para obter a resposta a ser testada.
4) Realizar uma série de asserções para verificar o funcionamento correto do que está sendo testado.  

Assim, para organizar visualmente e na minha cabeça também, eu sempre tendo a adicionar essas linhas em branco pra separar cada uma dessas etapas.

Mas concordo contigo que não tem necessidade nesse teste :smile:

2019-02-04 14:26 UTC, viniagostini commented on test/spreadsheets.js
> +const { readFileAsync } = require('./test_utils');
Concordo :smile:

2019-02-04 14:27 UTC, danielfireman commented on test/xlsx_service.test.js
> +
Entendi sim. A organização é boa

2019-02-05 01:15 UTC, danielfireman approved these changes

2019-02-05 01:15 UTC, merged