Add api error structure
dadosjusbr/parser pull request #6
Opened 2019-02-11 19:43 UTC by viniagostini

2019-02-11 21:08 UTC, danielfireman requested changes

2019-02-11 21:08 UTC, danielfireman commented on src/APIError.js
> +    this.stack || Error.captureStackTrace(this, this.constructor.name);
Isso me parece errado. Não deveria ser?

```js
this.stack = stack || Error.captureStackTrace(this, this.constructor.name); ?
```

2019-02-11 21:08 UTC, danielfireman commented on src/parser_service.js
> +const APIError = require('./APIError');
Esse nome de arquivo em maiúsculo é comum em JS? Não segue o padrão que você vinha usando até então.

2019-02-11 21:08 UTC, danielfireman commented on src/parser_service.js
> +    next(e);
Rapaz, honestamente não curti encadear com um middeware que trata erros.  Esse idioma de next e middlewares é bem comum em Go, mas em geral não usamos ele para tratamento de erros.

Sugestão: ou você cria um error handler geral (em Go acho que permitem adicionar um tratador geral de erros) ou trata o erro aqui mesmo.

Note que o problema aqui é a chamada `next`.  Quando que você poderia simplesmente fazer:

```js
handleError(res, e);
```

E acho que fica bem mais claro.

2019-02-12 14:15 UTC, viniagostini commented on src/APIError.js
> +    this.stack || Error.captureStackTrace(this, this.constructor.name);
Se a API desse `Error.captureStackTrace` fosse bacana seria sim. Mas na verdade o comportamento desse cara é modificar a property `stack` de um objeto passado no primeiro parâmetro dessa função. Em vez de retornar o stackTrace que seria, na minha opinião, muito melhor.

Nessa linha, eu estou tirando proveito de lazy evaluation e da coerção de javascript que consegue transformar qualquer coisa em truthy ou falsy.

É como se eu estivesse escrevendo:
```javascript
if (this.stack is undefined) {
    Error.captureStackTrace(this, this.constructor.name);
}
```

2019-02-12 14:22 UTC, viniagostini commented on src/parser_service.js
> +const APIError = require('./APIError');
Pois é, fiquei um tempo pensando nesse cara, porque de fato foge do padrão de nomenclatura que estamos adotando, no entanto, por convenção, todos os nomes de classes e funções construturas (forma antiga de criar algo parecido com uma classe) devem começar em maiúsculo.   

Assim, como esse arquivo apenas exporta uma classe, é como se ele representasse uma entidade da nossa aplicação e decidi deixar o nome dele em maiúsculo.  

Mas não sei se ficou bacana, o que tu acha?

2019-02-12 14:27 UTC, viniagostini commented on src/parser_service.js
> +    next(e);
Essa é a forma que a biblioteca sugere que o tratamento de erros seja feito, mas acho que para o nosso domínio (apenas uma rota) a tua sugestão fique bem mais legível e simples, vou implementar.

2019-02-12 14:29 UTC, danielfireman commented on src/parser_service.js
> +const APIError = require('./APIError');
Entendi sim. Pensei um pouco aqui e eu chamaria o  arquivo de `api_error.js` e manteria o nome da classe como está.

2019-02-12 14:33 UTC, viniagostini commented on src/parser_service.js
> +    next(e);
Feito :smile:

2019-02-12 14:37 UTC, viniagostini commented on src/parser_service.js
> +    next(e);
Outra coisa que eu queria discutir contigo antes de fazer o merge desse PR é a segunte:  

Não sei se tu notou, mas quando o parse da panilha é realizado com sucesso, o formato de resposta é CSV e quando algum erro ocorre é JSON. 

Isso me incomoda um pouco. O que tu acha?

2019-02-12 14:42 UTC, viniagostini commented on src/parser_service.js
> +const APIError = require('./APIError');
Feito :smile:

2019-02-12 14:49 UTC, danielfireman commented on src/parser_service.js
> +    next(e);
Entendo. Notei sim e, a priori, isso não é um problema. Uma coisa que podemos fazer para normalizar a coisa é o retorno ser sempre um JSON. Claro que os status codes também devem mudar, se houver erro de parsing o status code tem que ser diferente de 200.

Quando o parse for efetuado com sucesso, o status code é 200 e no corpo temos um JSON com informações a respeito da planilha, por exemplo, a URL que foi passada como parâmetro, o schema do CSV de retorno, a versão do esquema e, por fim, a planilha em si pode ser um campo do próprio JSON. Isso parece uma bala para matar uma mosca, mas nos dá o poder de facilmente identificar se houve mudança no esquema de dados entre o parse de dois arquivos de um mesmo mês. Quand o parse for efetuado com sucesso, o campo message ou erro vem vazio.

Quando houver um erro, o status code é diferente de 200 e retorna também um JSON, só que com o campo message ou erro preenchido.

2019-02-19 04:11 UTC, merged