add get schema endpoint
dadosjusbr/parser pull request #7
Opened 2019-02-19 04:13 UTC by viniagostini

2019-02-20 11:55 UTC, danielfireman requested changes

2019-02-20 11:55 UTC, danielfireman commented on src/schema_service.js
> +const _loadSchema = async () => {
Pessoal: acho bem desnecessário adicionar uma função que contém apenas 2 linhas e está logo acima da função que usa ela. Recomendo mover essas duas linhas de conteúdo para a função abaixo.

Caso essa função exista por causa dos testes (separar o carregamento do arquivo do resto), minha sugestão é que o schema não seja um arquivo .json e sim um arquivo .js. Dessa forma ele pode ser carregado como uma dependência qualquer e "viver" na memória.  

Mas enfim, fica a vontade para fazer como preferir.

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Cpf do Magistrado",
CPF

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "O Cpf do Magistrado (geralmente não informado nas planilhas)"
CPF

O que quer dizer "geralmente não informado nas planilhas". A coluna existe e não vai ser preenchida?

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "type": "nunber",
number

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Salário recebido pelo magistrado"
Adicionar campo: decimalChar: ","

https://frictionlessdata.io/specs/table-schema/

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Diretiros Pessoais",
Direitos

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Total recebido através de direitos pessoais"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Total recebido através de indenizações"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Total recebido através de direitos eventuais"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Total de rendimentos do Magistrado"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Desconto relativo a previdência pública sobre os rendimentos do Magistrado"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Desconto relativo a imposto de renda sobre os rendimentos do Magistrado"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Descontos não especificados.Podem incluir qualquer outro desconto de caráter não-pessoal"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Corte nas remunerações por exceder teto de salário de servidores públicos, limitado ao salário dos ministros do STF"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Retenção por Teto Constitucional",
teto constitucional (ao invés de Teto Constitucional)

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Somatório de todos os descontos aplicados à remuneração do Magistrado"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "name": "rendimento_liquido",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Recebimentos do tribunal onde o Magistrado 'entrou' no Judiciário"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Reembolso por despesas em serviços externos: alimentação, transporte, hospedagem e outros"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Bônus concedido a quem alcançou os requisitos para se aposentar, mas optou por permanecer em atividade"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "name": "subsidio_outra1",
subsidio_outro1 ?

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "type": "number",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "name": "subsidio_outra2",
subsidio_outro2 ?

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "type": "number",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Total de Direitos Pessoais",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "type": "number",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Também conhecido como auxílio creche, objetiva oferecer assistência ao atendimento de seus dependentes em idade pré-escolar"
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "type": "number",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Auxílio Natalidade",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Auxílio Moradia",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Ajuda de Custo",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "name": "indenizacoes_outra1",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "type": "number",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "name": "total_indenizacoes",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Abono Constitucional de 1/3 de férias",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Indenização de Férias",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Antecipação de Férias",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Gratificação Natalina",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Antecipação de Gratificação Natalina",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "type": "number",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Gratificação por Exercício Cumulativo",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "type": "number",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "title": "Pagamentos em Retroativos",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "type": "number",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "name": "direitos_eventuais_outra1",
direitos_eventuais_outro1 ?

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "description": ""
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "name": "direitos_eventuais_outra2",
direitos_eventuais_outro2 ?

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "type": "number",
Adicionar campo: decimalChar: ","

2019-02-20 11:55 UTC, danielfireman commented on src/resources/schema.json
> +        "name": "total_de_direitos_eventuais",
Adicionar campo: decimalChar: ","

2019-02-20 20:02 UTC, viniagostini commented on src/schema_service.js
> +const _loadSchema = async () => {
Massa! Foi justamente por conta dos testes. Lá no teste do endpoint `/schema`, eu faço um stub dessa função pra controlar o retorno dela, assim, eu posso verificar que o endpoint está retornando corretamente o schema sem me preocupar com o que de fato tem no schema.

Gostei da ideia do .js :smile:

2019-02-25 00:11 UTC, viniagostini commented on src/resources/schema.json
> +        "description": "O Cpf do Magistrado (geralmente não informado nas planilhas)"
A coluna as vezes é preenchida com dados reais pelos tribunais, mas em geral vem como: ***.***.***-** ou 000.000.000-00. 
Assim, decidi manter essa coluna CPF, mas coloquei isso pra indicar que raramente o CPF real estará nos dados.

2019-02-25 00:17 UTC, viniagostini commented on src/resources/schema.json
> +        "description": "Salário recebido pelo magistrado"
O valor que pretendo retornar é no formato default com o `.` sendo o decimalChar, tu acha que precisa adicionar o campo mesmo assim?

2019-02-25 00:23 UTC, viniagostini commented on src/resources/schema.json
> +        "name": "subsidio_outra1",
Isso é um dos campos da aba de subsídios, mas quase todas as abas tem um ou mais desses, eu decidi manter o mesmo nome da coluna.  
![image](https://user-images.githubusercontent.com/12215291/53307737-95172b80-387a-11e9-88b7-04e735c82bde.png)

2019-02-25 00:25 UTC, viniagostini commented on src/schema_service.js
> +const _loadSchema = async () => {
feito

2019-02-25 00:25 UTC, viniagostini commented on src/resources/schema.json
> +        "title": "Cpf do Magistrado",
feito

2019-02-25 00:25 UTC, viniagostini commented on src/resources/schema.json
> +        "type": "nunber",
feito

2019-02-25 00:26 UTC, viniagostini commented on src/resources/schema.json
> +        "title": "Diretiros Pessoais",
feito

2019-02-25 00:26 UTC, viniagostini commented on src/resources/schema.json
> +        "title": "Retenção por Teto Constitucional",
feito

2019-02-25 02:00 UTC, danielfireman commented on src/resources/schema.json
> +        "description": "Salário recebido pelo magistrado"
Se você vai retornar com ".", não precisa.

Acho tranquilo mudar, mas por que a ideia de ralizar a conversão? Pelo que vi na planilha usa "," como separador dos decimais.

2019-02-25 02:01 UTC, danielfireman approved these changes

2019-02-25 15:36 UTC, viniagostini commented on src/resources/schema.json
> +        "description": "Salário recebido pelo magistrado"
Esses campos com valores monetários estão bem despadronizados nas planilhas, assim, a gente ja ia ter que realizar um tratamento pra extrair esses caras. Com isso, achei que seria uma feature legal essa conversão.

2019-02-25 15:50 UTC, danielfireman approved these changes

2019-02-25 15:50 UTC, merged